name: Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        framework: ["net8.0", "net10.0"]
    name: ${{ matrix.framework }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            10.0.x
      - name: Test
        run: dotnet test tests/Duta.Tests -f ${{ matrix.framework }}
